Timeline problem set updates
Ada-Developers-Academy/core-unit-3 pull request #120
Opened 2023-12-18 21:28 UTC by yangashley

Updates for "Port "Props/Problem Set: Timeline" to use npm/vite": https://app.asana.com/0/1205655776549324/1205941930814359/f

2023-12-18 22:22 UTC, anselrognlie requested changes
There are a few other changes I think we should make while were here. What do you think?

2023-12-18 22:22 UTC, anselrognlie commented on props/problem-set-timeline.md
> +In our projects folder, create a new React app named `timeline` with the following command:
Mixture of voicing (our v. command)

```suggestion
In our projects folder, we'll create a new React app named `timeline` with the following command:
```

2023-12-18 22:22 UTC, anselrognlie commented on props/problem-set-timeline.md
It still bothers me that we call Timeline.jsx a Container component rather than Presentational. It doesn't own any of the data (it receives timeline data from the App). But maybe it's fine to leave it as is to bring it up in discussion? What do you think?

2023-12-18 22:35 UTC, yangashley commented on props/problem-set-timeline.md
> +  <code>src/components/TimeStamp.js</code>
Ok sounds good, I'll add the proptypes to all the components for consistency

2023-12-18 22:39 UTC, anselrognlie commented on props/problem-set-timeline.md
> +  <code>src/components/TimeStamp.js</code>
Like just an empty proptype to give students a place to add theirs? We don't explicitly say what to use for the prop attribute names or types, so I'd lean towards leaving the rest of them open. TimeLine is the only one we provide fully implemented.

2023-12-18 22:45 UTC, yangashley commented on props/problem-set-timeline.md
I guess the reason Timeline.jsx is called a container component is because in the "Nested Components" lesson we say "Container components are components responsible for sending data to presentation components". So according to our definition it can be interpreted as a container component. 

We could leave it and then have a discussion in RT like you said and also bring up that this isn't the be-all and end-all distinction for types of components. Does that work?

2023-12-18 22:50 UTC, anselrognlie commented on props/problem-set-timeline.md
That's fine with me. It's more of a pet peave for me. In my view, it's more of a passthru. It's given exactly the data display without needing to know how to manage it itself. I draw the distinction closer to the knowing how to manage data line.

2023-12-18 23:32 UTC, yangashley commented on props/problem-set-timeline.md
> +  <code>src/components/TimeStamp.js</code>
Oh ha, that's right. I was looking at my own fully implemented version. Will make the update for Timeline!

2023-12-19 17:33 UTC, anselrognlie commented on props/problem-set-timeline.md
Data updates look good. Just need to update the screenshot.

2023-12-19 17:35 UTC, anselrognlie approved these changes
LGTM. Just needs the screenshot updated.

2023-12-19 22:07 UTC, merged