Update use effect and calling apis
Ada-Developers-Academy/core-unit-3 pull request #130
Opened 2024-01-08 20:57 UTC by yangashley

https://app.asana.com/0/1205655776549324/1206303695912559/f

2024-01-08 21:23 UTC, yangashley commented on useeffect-and-calling-apis/useeffect-after-render.md
On line 21 of this lesson, we link to a now legacy React document about the component lifecycle. I've been searching for an equivalent in the new React docs but don't see any. 

There's this doc that makes mention of the component lifecycle but it's in comparison to the effect's lifecycle: https://react.dev/learn/lifecycle-of-reactive-effects

Do you think it's ok to leave the legacy link?

2024-01-08 22:10 UTC, anselrognlie commented on useeffect-and-calling-apis/useeffect-after-render.md
The closest I can find to the lifecycle stuff is at https://react.dev/reference/react/Component#adding-lifecycle-methods-to-a-class-component. But do we even need to keep the component lifecycle stuff? The newer documentation sounds like it encourages thinking more along the lines of starting and stopping synchronization.

With hooks components, since the entire component function always runs, I don't know how usesful the lifecycle material is. It was more useful to help keep track of which class component methods got called when, but given that Ada has never (to my knowledge) taught class components, it doesn't seem to provide much aid in understanding.

But if reworking this material seems too large to do now, I'd probably just leave the link as is.

2024-01-08 22:28 UTC, yangashley commented on useeffect-and-calling-apis/useeffect-after-render.md
Ok, I'll leave it for now so we can move on to other stories. I'll make a card though about updating this lesson to get rid of the life cycle stuff so we can revisit later.

2024-01-08 22:49 UTC, yangashley commented on useeffect-and-calling-apis/useeffect-after-render.md
https://app.asana.com/0/1201700438643002/1206304754953616/f

2024-01-08 23:25 UTC, anselrognlie requested changes
The main changes look fine to me. There are a few images that seem to have gotten larger (and won't preview properly) and then there are a couple extraneous suggestions I have. Details in the comments.

2024-01-08 23:25 UTC, anselrognlie commented on useeffect-and-calling-apis/calling-apis-from-components.md
In the alt text for one of the images Learn won't show me, there's a typo. In the alt text for `_Fig. Viewing the network request in the browser Dev Tools Network tab_`(around line 320 for me), retuning should be returning.

So I guess thanks Learn?

2024-01-08 23:25 UTC, anselrognlie commented on useeffect-and-calling-apis/calling-apis-from-components.md
The first two challenges on this are problematic for a lot of students. They often include `import useState` even though the prompts don't say anything that would require it.

Would it be possible to add some hints to help the reader think a bit more deeply about each of the options?

2024-01-09 17:10 UTC, yangashley commented on assets/useeffect-and-calling-apis_calling-apis-from-components_button-console-log.png
I had to blow up the image to see it to take a screenshot because I was only working with my laptop monitor yesterday. I didn't think that they would get big enough to throw the error. I'll shrink them and try again!

2024-01-10 19:45 UTC, anselrognlie approved these changes
LGTM

2024-01-10 19:46 UTC, merged