adds first portfolio activity to structuring content
Ada-Developers-Academy/core-unit-3 pull request #70
Opened 2021-11-10 02:05 UTC by spitsfire

it's currently missing a correct Ada C16 repo link

2021-11-10 16:41 UTC, CheezItMan requested changes
I suggest that we either comment out for this cohort or remove "Part 4: Recreate One of These Resumes" in the problemset.  Just because that's supposed to take "3 hours".  This covers that learning goal, and honestly does a better job.

Otherwise this is good, I would also suggest they employ an ordered or unordered list.

2021-11-10 16:41 UTC, CheezItMan commented on structuring-content/activity-personal-portfolio-1.md
> +- `portfolio.html`
I suggest we use something like what we did in the JS sections.  Although it won't let me insert 3 backtics around it to make it look better. 

```suggestion
.
├── index.html
├── about.html
└── portfolio.html
```

2021-11-10 16:41 UTC, CheezItMan commented on structuring-content/activity-personal-portfolio-1.md
> +- `portfolio.html` must include information about the projects you've completed at Ada (or elsewhere) with links to GitHub repo if available, descriptions, images, etc.
```suggestion
- `portfolio.html` must include information about several projects you've completed at Ada (or elsewhere) with links to the GitHub repo if available, descriptions, images, etc.
```

2021-11-10 18:33 UTC, spitsfire commented on structuring-content/activity-personal-portfolio-1.md
> +└── portfolio.html
```suggestion
├── `index.html`
├── `about.html`
└── `portfolio.html`
```

2021-11-11 00:06 UTC, CheezItMan approved these changes

2021-11-11 00:23 UTC, jericahuang approved these changes

2021-11-11 19:29 UTC, merged